- menu_name: "Misc"

- name: "Contact us"
  url: "/contact/index.html"
  title: "Contact"

- name: "RSS"
  url: "/feed.xml"
  title: "Subscribe to RSS Feed"

- name: "Privacy Policy"
  url: "/privacypolicy/index.html"
  title: "Our Private Policy"

- name: "Terms and Conditions"
  url: "/termsandconditions/index.html"
  title: "Our Terms and Conditions"
